import mongoose from "mongoose";

const InvoiceDetailSchema = new mongoose.Schema({
	idhdon: { type: String },
	id: { type: String },
	dgia: { type: Number },
	dvtinh: { type: String },
	ltsuat: { type: String },
	sluong: { type: Number },
	stckhau: { type: Number },
	stt: { type: Number },
	tchat: { type: Number },
	ten: { type: String },
	thtien: { type: Number },
	tlckhau: { type: Number },
	tsuat: { type: Number },
	sxep: { type: Number },
	stbchu: { type: String },
	thtcthue: { type: Number },
	tthue: { type: Number },
	ttkhac: [
		{
			ttruong: String,
			kdlieu: String,
			dlieu: mongoose.Schema.Types.Mixed,
		},
	],
});

const InvoicesInSchema = new mongoose.Schema(
	{
		ownerId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "BusinessOwner",
			required: true,
			index: true,
		},
		nmstatus: { type: String },
		nbstatus: { type: String },
		htmlContent: { type: String },
		nbmst: { type: String },
		khmshdon: { type: Number },
		khhdon: { type: String },
		shdon: { type: Number },
		cqt: { type: String },
		cttkhac: [
			{
				ttruong: String,
				kdlieu: String,
				dlieu: mongoose.Schema.Types.Mixed,
			},
		],
		dvtte: { type: String },
		hdon: { type: String },
		hsgcma: { type: String },
		hsgoc: { type: String },
		hthdon: { type: Number },
		htttoan: { type: String },
		id: { type: String },
		idtbao: { type: String },
		khdon: { type: String },
		khhdgoc: { type: String },
		khmshdgoc: { type: String },
		lhdgoc: { type: String },
		mhdon: { type: String },
		mtdiep: { type: String },
		mtdtchieu: { type: String },
		nbdchi: { type: String },
		nbhdktngay: { type: Date },
		nbhdktso: { type: String },
		nbhdso: { type: String },
		nblddnbo: { type: String },
		nbptvchuyen: { type: String },
		nbstkhoan: { type: String },
		nbten: { type: String },
		nbtnhang: { type: String },
		nbtnvchuyen: { type: String },
		nbttkhac: [
			{
				ttruong: String,
				kdlieu: String,
				dlieu: mongoose.Schema.Types.Mixed,
			},
		],
		ncma: { type: Date },
		ncnhat: { type: Date },
		ngcnhat: { type: String },
		nky: { type: Date },
		nmdchi: { type: String },
		nmmst: { type: String },
		nmten: { type: String },
		nmttkhac: [
			{
				ttruong: String,
				kdlieu: String,
				dlieu: mongoose.Schema.Types.Mixed,
			},
		],
		nmsdthoai: { type: String },
		nmdctdtu: { type: String },
		nmcmnd: { type: String },
		nmcks: { type: String },
		ntao: { type: Date },
		ntnhan: { type: Date },
		pban: { type: String },
		ptgui: { type: Number },
		tchat: { type: Number },
		tdlap: { type: Date },
		tgia: { type: Number },
		tgtcthue: { type: Number },
		tgtthue: { type: Number },
		tgtttbchu: { type: String },
		tgtttbso: { type: Number },
		thdon: { type: String },
		thlap: { type: Number },
		thttlphi: [{ type: mongoose.Schema.Types.Mixed }],
		thttltsuat: [
			{
				tsuat: String,
				thtien: Number,
				tthue: Number,
				gttsuat: mongoose.Schema.Types.Mixed,
			},
		],
		tlhdon: { type: String },
		ttcktmai: { type: Number },
		tthai: { type: Number },
		ttkhac: [
			{
				ttruong: String,
				kdlieu: String,
				dlieu: mongoose.Schema.Types.Mixed,
			},
		],
		tttbao: { type: Number },
		ttttkhac: [
			{
				ttruong: String,
				kdlieu: String,
				dlieu: mongoose.Schema.Types.Mixed,
			},
		],
		ttxly: { type: Number },
		tvandnkntt: { type: String },
		thtttoan: { type: String },
		msttcgp: { type: String },
		gchu: { type: String },
		hdhhdvu: [InvoiceDetailSchema],
		qrcode: { type: String },
		tchatbchu: { type: String },
		tthaibchu: { type: String },
		nbwebsite: { type: String },
		nbcks: { type: String },
		nbsdthoai: { type: String },
		nbdctdtu: { type: String },
		nbfax: { type: String },
		bhphap: { type: Number },
		hddunlap: { type: String },
		gchdgoc: { type: String },
		tbhgtngay: { type: Date },
		bhpldo: { type: String },
		bhpcbo: { type: String },
		bhpngay: { type: Date },
		tdlhdgoc: { type: String },
		tgtphi: { type: Number },
		unhiem: { type: String },
		mstdvnunlhdon: { type: String },
		tdvnunlhdon: { type: String },
		nbmdvqhnsach: { type: String },
		nbsqdinh: { type: String },
		nbncqdinh: { type: String },
		nbcqcqdinh: { type: String },
		nbhtban: { type: String },
		nmmdvqhnsach: { type: String },
		nmddvchden: { type: String },
		nmtgvchdtu: { type: String },
		nmtgvchdden: { type: String },
		nbtnban: { type: String },
		dcdvnunlhdon: { type: String },
		dksbke: { type: String },
		dknlbke: { type: String },
		cqtcks: { type: String },
		kqcht: { type: String },
		hdonLquans: { type: mongoose.Schema.Types.Mixed },
		tthdclquan: { type: Boolean },
		pdndungs: { type: mongoose.Schema.Types.Mixed },
		hdtbssrses: { type: mongoose.Schema.Types.Mixed },
		hdgktkhthue: { type: mongoose.Schema.Types.Mixed },
		hdxkhau: { type: mongoose.Schema.Types.Mixed },
		hdxkptquan: { type: mongoose.Schema.Types.Mixed },
		ladhddt: { type: Number },
		ladhddtten: { type: String },
		mhso: { type: String },
		mkhang: { type: String },
		shdgoc: { type: String },
		tbhgtngay: { type: Date },
	},
	{ timestamps: true }
);

InvoicesInSchema.index({ ownerId: 1, mhdon: 1 }, { unique: true });

const InvoicesIn = mongoose.model("InvoicesIn", InvoicesInSchema);
export default InvoicesIn;
